# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
[workspace]

[workspace.package]
version = "0.2.2"
edition = "2021"
license = "MPL-2.0"
authors = ["touchHLE project contributors"]
homepage = "https://touchhle.org/"

[package]
name = "touchHLE"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }

[lib]
# https://users.rust-lang.org/t/making-both-binary-and-cdylib-from-one-package/29105
crate_type = ["cdylib", "rlib"]

[[bin]]
name = "touchHLE"
path = "src/bin.rs"

[features]
default = ["static"]
static = ["sdl2/bundled", "sdl2/static-link", "touchHLE_openal_soft_wrapper/static"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
cc = "1.0.83"
cmake = "0.1.49"
gl_generator = "0.14.0"

[dependencies]
caf = "0.1.0"
hound = "3.5.0"
mach_object = "0.1.17"
plist = "1.3.1"
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }
rusttype = "0.9.3"
# Symphonia is only used by src/audio/aac.rs right now, so that determines the
# supported features. Only the AAC-LC profile (the "aac" feature) should be
# enabled, because it's old enough that it *probably* isn't patent-encumbered,
# but IANAL. Newer AAC profiles on the other hand are nightmares.
symphonia = { version = "0.5.3", default-features = false, features = ["aac", "isomp4"] }
# We currently use a fork of rust-sdl2 because we need a fix for Android builds
# that's not upstream yet.
# The HIDAPI feature is enabled because rust-sdl2 hides the SDL2 sensor features
# behind this, but the actual HIDAPI is not used by touchHLE (see window.rs).
# Note that the submodule in vendor/SDL2/ must use exactly the same revision of
# SDL2 that rust-sdl2 uses, so that the Android JNI interface matches.
sdl2 = { git = "https://github.com/hikari-no-yume/rust-sdl2.git", tag = "touchHLE-2", features = ["hidapi"] }
sdl2-sys = { git = "https://github.com/hikari-no-yume/rust-sdl2.git", tag = "touchHLE-2" }

[build-dependencies]
cargo-license = "0.5.1"
cc = { workspace = true }
cmake = { workspace = true }
gl_generator = { workspace = true }
